// Writes docs/media-inventory.json + docs/MEDIA_INVENTORY.md from the files on disk.
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const origin = {
  'cheezy/showcase-desktop': 'Recorded from www.cheezy.store (CDP screencast, scripted: home → ordering section → story → Menu → shop picker → menu → Cappuccino sheet)',
  'cheezy/showcase-mobile': 'Recorded from www.cheezy.store at 390×844 (iPhone 13 profile)',
  'cheezy/app-mobile': 'Recorded from cheezy-app-demo.vercel.app (onboarding → shop choice → home)',
  'cheezy/film-app': 'Re-encoded from cheezy/LIVRAISON/Cheezy-Film-II.mp4 (Ahmed\'s own launch film for the client)',
  'radar/showcase-desktop': 'Recorded from math.project/radar_3d_demo_equations_v2.html (self-running, GPU rendering)',
  'scraping/showcase-desktop': 'Recorded from the local Flask + React app (home narrative → dashboard → prediction)',
  'subway-runner/showcase-desktop': 'WebGL build of a temporary copy of SubwayRunner; two real gameplay takes joined with a 0.6 s crossfade',
  'radar/fig-': 'Copied from math.project/results (matplotlib output of the project)',
  'cheezy/ad-': 'From cheezy/ads/approved (client-approved creatives)',
  'profile/': 'Face Picture.png, cut out (edge flood-fill mask), monochrome + colour',
  'og/': 'Rendered from the built site (scripts/og/render.mjs)',
  'intros/': 'Neutral poster rendered from the site\'s iris (scripts/og/render.mjs)',
};
const why = (rel) => Object.entries(origin).find(([k]) => rel.includes(k))?.[1] ?? 'Playwright screenshot of the real project (scripts/media/scenarios.mjs → stills)';

const rows = [];
const walk = (d) => fs.readdirSync(d, { withFileTypes: true }).forEach((e) => {
  const p = path.join(d, e.name);
  if (e.isDirectory()) return walk(p);
  if (/-sm\.webp$/.test(e.name)) return;
  const rel = p.split(path.sep).join('/').replace(/^public\//, '');
  const size = fs.statSync(p).size;
  let info = {};
  try {
    const out = execFileSync('ffprobe', ['-v', 'error', '-select_streams', 'v:0', '-show_entries', 'stream=width,height:format=duration', '-of', 'json', p], { encoding: 'utf8' });
    const j = JSON.parse(out);
    info = { width: j.streams?.[0]?.width, height: j.streams?.[0]?.height, duration: j.format?.duration && /\.(mp4|webm)$/.test(p) ? Number(Number(j.format.duration).toFixed(1)) : undefined };
  } catch {}
  rows.push({ file: rel, kb: Math.round(size / 1024), ...info, source: why(rel) });
});
walk('public/media');
walk('public/og');
fs.writeFileSync('docs/media-inventory.json', JSON.stringify(rows, null, 1));
const md = ['# Media inventory', '', 'Generated by `node scripts/media/inventory.mjs` from the files on disk. Responsive `-sm.webp` halves are omitted. Every film and screenshot shows the real project; nothing is mocked.', '', '| File | Size | Dimensions | Duration | Source / method |', '|---|---:|---|---:|---|',
  ...rows.map((r) => `| \`${r.file}\` | ${r.kb} KB | ${r.width ? r.width + '×' + r.height : ''} | ${r.duration ? r.duration + ' s' : ''} | ${r.source} |`),
  '', '## Quality control performed', '', '- Every film reviewed as a contact sheet (one frame every 0.8–1.5 s) for loading states, cursor, browser chrome, blank frames, scroll jumps and error states.',
  '- Rejected and re-shot: Cheezy desktop (too long → trimmed to 19.6 s), Books film (Prediction view opened at a stale scroll position), Cheezy app film (splash frame + static tail), radar film (software-GL z-fighting → re-recorded with GPU), SubwayRunner (takes ending in "Game Over" were discarded).',
  '- Stills not used: Sandy AI Lab mobile (the hackathon build overflows at 390 px).',
  '', '## Not captured, and why', '', '- **AI Eyes Android app** — requires a physical device + camera; no emulator image available. Drop a real screen recording at `public/media/projects/aieyes/showcase-mobile.mp4` (+ `-poster.webp`) and it appears on the home page and case study automatically.',
  '- **AI Eyes dashboard (signed in)** — private family data behind the owner\'s credentials.',
  '- **Sandy AI Lab answering** — the Groq key in `sandy-ai-lab/.env` is expired; re-record with a valid key via `npm run media -- ...` (see README).',
];
fs.writeFileSync('docs/MEDIA_INVENTORY.md', md.join('\n') + '\n');
console.log(rows.length, 'media files inventoried');
